/**
 * build.js — Nano Banana Pro Prompt Explorer
 * Run once:  node build.js
 *
 * Reads nano-banana-pro-prompts-*.csv  →  outputs data.js
 * After that, index.html loads instantly with no upload needed.
 */

const fs   = require('fs');
const path = require('path');

// ── Find the CSV ──────────────────────────────────────────────
const dir   = __dirname;
const files = fs.readdirSync(dir).filter(f => f.endsWith('.csv'));
if (files.length === 0) {
  console.error('❌  No .csv file found in', dir);
  process.exit(1);
}
const csvFile = files[0];
console.log(`📂  Reading ${csvFile}…`);

const raw = fs.readFileSync(path.join(dir, csvFile), 'utf8');
console.log(`    ${(raw.length / 1024 / 1024).toFixed(1)} MB read`);

// ── CSV state-machine parser (matches app.js logic) ───────────
function parseCSV(text) {
  const rows = [];
  const n = text.length;
  let i = 0;

  function parseField() {
    if (text[i] === '"') {
      i++;
      let val = '';
      while (i < n) {
        if (text[i] === '"') {
          if (text[i + 1] === '"') { val += '"'; i += 2; }
          else { i++; break; }
        } else { val += text[i++]; }
      }
      return val;
    } else {
      let val = '';
      while (i < n && text[i] !== ',' && text[i] !== '\n' && text[i] !== '\r')
        val += text[i++];
      return val;
    }
  }

  function parseRow() {
    const fields = [];
    while (i < n) {
      fields.push(parseField());
      if (text[i] === ',')  { i++; continue; }
      if (text[i] === '\r')   i++;
      if (text[i] === '\n') { i++; break; }
      if (i >= n) break;
    }
    return fields;
  }

  const headers = parseRow();
  const hIdx = {};
  headers.forEach((h, idx) => { hIdx[h.trim()] = idx; });

  let count = 0;
  while (i < n) {
    if (text[i] === '\r' || text[i] === '\n') { i++; continue; }
    const fields = parseRow();
    if (fields.length < 2) continue;

    const get = (k) => fields[hIdx[k]] ?? '';

    let author = { name: '', link: '' };
    try { const r = get('author'); if (r) author = JSON.parse(r); } catch {}

    let media = [];
    try { const r = get('sourceMedia'); if (r) media = JSON.parse(r); } catch {}

    rows.push({
      id:          get('id'),
      title:       get('title'),
      description: get('description'),
      content:     get('content'),
      sourceLink:  get('sourceLink'),
      publishedAt: get('sourcePublishedAt'),
      author,
      media,
    });

    count++;
    if (count % 1000 === 0) process.stdout.write(`\r    Parsed ${count.toLocaleString()} rows…`);
  }

  process.stdout.write('\n');
  return rows;
}

// ── Parse ─────────────────────────────────────────────────────
console.log('⚙️   Parsing…');
const data  = parseCSV(raw);
console.log(`✅  Parsed ${data.length.toLocaleString()} prompts`);

// ── Write data.js ─────────────────────────────────────────────
console.log('💾  Writing data.js…');
const json   = JSON.stringify(data);
const output = `/* AUTO-GENERATED by build.js — do not edit manually */\nwindow.PROMPT_DATA=${json};`;
const outPath = path.join(dir, 'data.js');
fs.writeFileSync(outPath, output, 'utf8');

const sizeMB = (fs.statSync(outPath).size / 1024 / 1024).toFixed(1);
console.log(`\n🍌  Done!  data.js written (${sizeMB} MB)`);
console.log('    Open index.html in your browser — no upload needed anymore.\n');
